apiVersion: v1
kind: Service   
metadata:
  name: argocd-app-service
spec:
  selector:
    app.kubernetes.io/name: argocd-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
